
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../media/base/container_names.h

package org.chromium.media;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    MediaContainerName.CONTAINER_UNKNOWN, MediaContainerName.CONTAINER_AAC,
    MediaContainerName.CONTAINER_AC3, MediaContainerName.CONTAINER_AIFF,
    MediaContainerName.CONTAINER_AMR, MediaContainerName.CONTAINER_APE,
    MediaContainerName.CONTAINER_ASF, MediaContainerName.CONTAINER_ASS,
    MediaContainerName.CONTAINER_AVI, MediaContainerName.CONTAINER_BINK,
    MediaContainerName.CONTAINER_CAF, MediaContainerName.CONTAINER_DTS,
    MediaContainerName.CONTAINER_DTSHD, MediaContainerName.CONTAINER_DV,
    MediaContainerName.CONTAINER_DXA, MediaContainerName.CONTAINER_EAC3,
    MediaContainerName.CONTAINER_FLAC, MediaContainerName.CONTAINER_FLV,
    MediaContainerName.CONTAINER_GSM, MediaContainerName.CONTAINER_H261,
    MediaContainerName.CONTAINER_H263, MediaContainerName.CONTAINER_H264,
    MediaContainerName.CONTAINER_HLS, MediaContainerName.CONTAINER_IRCAM,
    MediaContainerName.CONTAINER_MJPEG, MediaContainerName.CONTAINER_MOV,
    MediaContainerName.CONTAINER_MP3, MediaContainerName.CONTAINER_MPEG2PS,
    MediaContainerName.CONTAINER_MPEG2TS, MediaContainerName.CONTAINER_MPEG4BS,
    MediaContainerName.CONTAINER_OGG, MediaContainerName.CONTAINER_RM,
    MediaContainerName.CONTAINER_SRT, MediaContainerName.CONTAINER_SWF,
    MediaContainerName.CONTAINER_VC1, MediaContainerName.CONTAINER_WAV,
    MediaContainerName.CONTAINER_WEBM, MediaContainerName.CONTAINER_WTV,
    MediaContainerName.CONTAINER_DASH, MediaContainerName.CONTAINER_SMOOTH_STREAM,
    MediaContainerName.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface MediaContainerName {
  int CONTAINER_UNKNOWN = 0;
  int CONTAINER_AAC = 1;
  int CONTAINER_AC3 = 2;
  int CONTAINER_AIFF = 3;
  int CONTAINER_AMR = 4;
  int CONTAINER_APE = 5;
  int CONTAINER_ASF = 6;
  int CONTAINER_ASS = 7;
  int CONTAINER_AVI = 8;
  int CONTAINER_BINK = 9;
  int CONTAINER_CAF = 10;
  int CONTAINER_DTS = 11;
  int CONTAINER_DTSHD = 12;
  int CONTAINER_DV = 13;
  int CONTAINER_DXA = 14;
  int CONTAINER_EAC3 = 15;
  int CONTAINER_FLAC = 16;
  int CONTAINER_FLV = 17;
  int CONTAINER_GSM = 18;
  int CONTAINER_H261 = 19;
  int CONTAINER_H263 = 20;
  int CONTAINER_H264 = 21;
  int CONTAINER_HLS = 22;
  int CONTAINER_IRCAM = 23;
  int CONTAINER_MJPEG = 24;
  int CONTAINER_MOV = 25;
  int CONTAINER_MP3 = 26;
  int CONTAINER_MPEG2PS = 27;
  int CONTAINER_MPEG2TS = 28;
  int CONTAINER_MPEG4BS = 29;
  int CONTAINER_OGG = 30;
  int CONTAINER_RM = 31;
  int CONTAINER_SRT = 32;
  int CONTAINER_SWF = 33;
  int CONTAINER_VC1 = 34;
  int CONTAINER_WAV = 35;
  int CONTAINER_WEBM = 36;
  int CONTAINER_WTV = 37;
  int CONTAINER_DASH = 38;
  int CONTAINER_SMOOTH_STREAM = 39;
  int MAX_VALUE = 39;
}
