// StableVideoDecoderConstants.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/mojom/stable/stable_video_decoder.mojom
//

package org.chromium.media.stable.mojom;

import androidx.annotation.IntDef;

public final class StableVideoDecoderConstants {


    
    public static final int STABLE_VIDEO_DECODER_FACTORY_SERVICE_SANDBOX = (int) org.chromium.sandbox.mojom.Sandbox.NO_SANDBOX;



    private StableVideoDecoderConstants() {}

}