
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../ui/android/resources/system_ui_resource_type.h

package org.chromium.android_webview.shell.Resources;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    SystemUIResourceType.OVERSCROLL_GLOW
})
@Retention(RetentionPolicy.SOURCE)
public @interface SystemUIResourceType {
  int OVERSCROLL_GLOW = 0;
}
