// AxConstantsConstants.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_constants.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class AxConstantsConstants {


    
    public static final int UNKNOWN_ARIA_COLUMN_OR_ROW_COUNT = (int) -1;



    private AxConstantsConstants() {}

}