// DefaultActionVerb.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class DefaultActionVerb {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        DefaultActionVerb.NONE,
        DefaultActionVerb.ACTIVATE,
        DefaultActionVerb.CHECK,
        DefaultActionVerb.CLICK,
        DefaultActionVerb.CLICK_ANCESTOR,
        DefaultActionVerb.JUMP,
        DefaultActionVerb.OPEN,
        DefaultActionVerb.PRESS,
        DefaultActionVerb.SELECT,
        DefaultActionVerb.UNCHECK})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int ACTIVATE = 1;
    public static final int CHECK = 2;
    public static final int CLICK = 3;
    public static final int CLICK_ANCESTOR = 4;
    public static final int JUMP = 5;
    public static final int OPEN = 6;
    public static final int PRESS = 7;
    public static final int SELECT = 8;
    public static final int UNCHECK = 9;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 9;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 9;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private DefaultActionVerb() {}
}