// Dropeffect.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class Dropeffect {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        Dropeffect.NONE,
        Dropeffect.COPY,
        Dropeffect.EXECUTE,
        Dropeffect.LINK,
        Dropeffect.MOVE,
        Dropeffect.POPUP})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int COPY = 1;
    public static final int EXECUTE = 2;
    public static final int LINK = 3;
    public static final int MOVE = 4;
    public static final int POPUP = 5;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 5;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 5;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private Dropeffect() {}
}