// HasPopup.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class HasPopup {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        HasPopup.FALSE,
        HasPopup.TRUE,
        HasPopup.MENU,
        HasPopup.LISTBOX,
        HasPopup.TREE,
        HasPopup.GRID,
        HasPopup.DIALOG,
        HasPopup.NONE})
    public @interface EnumType {}

    public static final int FALSE = 0;
    public static final int TRUE = 1;
    public static final int MENU = 2;
    public static final int LISTBOX = 3;
    public static final int TREE = 4;
    public static final int GRID = 5;
    public static final int DIALOG = 6;
    public static final int NONE = 0;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 6;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 6;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private HasPopup() {}
}