// HighlightType.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class HighlightType {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        HighlightType.NONE,
        HighlightType.HIGHLIGHT,
        HighlightType.SPELLING_ERROR,
        HighlightType.GRAMMAR_ERROR})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int HIGHLIGHT = 1;
    public static final int SPELLING_ERROR = 2;
    public static final int GRAMMAR_ERROR = 3;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 3;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 3;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private HighlightType() {}
}