// ImageAnnotationStatus.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class ImageAnnotationStatus {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        ImageAnnotationStatus.NONE,
        ImageAnnotationStatus.WILL_NOT_ANNOTATE_DUE_TO_SCHEME,
        ImageAnnotationStatus.INELIGIBLE_FOR_ANNOTATION,
        ImageAnnotationStatus.ELIGIBLE_FOR_ANNOTATION,
        ImageAnnotationStatus.SILENTLY_ELIGIBLE_FOR_ANNOTATION,
        ImageAnnotationStatus.ANNOTATION_PENDING,
        ImageAnnotationStatus.ANNOTATION_SUCCEEDED,
        ImageAnnotationStatus.ANNOTATION_EMPTY,
        ImageAnnotationStatus.ANNOTATION_ADULT,
        ImageAnnotationStatus.ANNOTATION_PROCESS_FAILED})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int WILL_NOT_ANNOTATE_DUE_TO_SCHEME = 1;
    public static final int INELIGIBLE_FOR_ANNOTATION = 2;
    public static final int ELIGIBLE_FOR_ANNOTATION = 3;
    public static final int SILENTLY_ELIGIBLE_FOR_ANNOTATION = 4;
    public static final int ANNOTATION_PENDING = 5;
    public static final int ANNOTATION_SUCCEEDED = 6;
    public static final int ANNOTATION_EMPTY = 7;
    public static final int ANNOTATION_ADULT = 8;
    public static final int ANNOTATION_PROCESS_FAILED = 9;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 9;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 9;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private ImageAnnotationStatus() {}
}