// MarkerType.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class MarkerType {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        MarkerType.NONE,
        MarkerType.SPELLING,
        MarkerType.GRAMMAR,
        MarkerType.TEXT_MATCH,
        MarkerType.ACTIVE_SUGGESTION,
        MarkerType.SUGGESTION,
        MarkerType.HIGHLIGHT})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int SPELLING = 1;
    public static final int GRAMMAR = 2;
    public static final int TEXT_MATCH = 4;
    public static final int ACTIVE_SUGGESTION = 16;
    public static final int SUGGESTION = 32;
    public static final int HIGHLIGHT = 64;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 64;

    public static boolean isKnownValue(int value) {
        switch (value) {
            case 0:
            case 1:
            case 2:
            case 4:
            case 16:
            case 32:
            case 64:
                return true;
        }
        return false;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private MarkerType() {}
}