// NameFrom.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class NameFrom {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        NameFrom.NONE,
        NameFrom.ATTRIBUTE,
        NameFrom.ATTRIBUTE_EXPLICITLY_EMPTY,
        NameFrom.CAPTION,
        NameFrom.CONTENTS,
        NameFrom.PLACEHOLDER,
        NameFrom.RELATED_ELEMENT,
        NameFrom.TITLE,
        NameFrom.VALUE,
        NameFrom.POPOVER_ATTRIBUTE})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int ATTRIBUTE = 1;
    public static final int ATTRIBUTE_EXPLICITLY_EMPTY = 2;
    public static final int CAPTION = 3;
    public static final int CONTENTS = 4;
    public static final int PLACEHOLDER = 5;
    public static final int RELATED_ELEMENT = 6;
    public static final int TITLE = 7;
    public static final int VALUE = 8;
    public static final int POPOVER_ATTRIBUTE = 9;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 9;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 9;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private NameFrom() {}
}