// TextDecorationStyle.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/accessibility/ax_enums.mojom
//

package org.chromium.ax.mojom;

import androidx.annotation.IntDef;

public final class TextDecorationStyle {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        TextDecorationStyle.NONE,
        TextDecorationStyle.DOTTED,
        TextDecorationStyle.DASHED,
        TextDecorationStyle.SOLID,
        TextDecorationStyle.DOUBLE,
        TextDecorationStyle.WAVY})
    public @interface EnumType {}

    public static final int NONE = 0;
    public static final int DOTTED = 1;
    public static final int DASHED = 2;
    public static final int SOLID = 3;
    public static final int DOUBLE = 4;
    public static final int WAVY = 5;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 5;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 5;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private TextDecorationStyle() {}
}