
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../content/public/browser/overlay_window.h

package org.chromium.content_public.browser.overlay_window;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    PlaybackState.PLAYING, PlaybackState.PAUSED, PlaybackState.END_OF_VIDEO
})
@Retention(RetentionPolicy.SOURCE)
public @interface PlaybackState {
  int PLAYING = 0;
  int PAUSED = 1;
  int END_OF_VIDEO = 2;
}
