// UsbDeviceConstants.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/device/public/mojom/usb_device.mojom
//

package org.chromium.device.mojom;

import androidx.annotation.IntDef;

public final class UsbDeviceConstants {


    
    public static final byte USB_AUDIO_CLASS = (byte) 1;



    
    public static final byte USB_HID_CLASS = (byte) 3;



    
    public static final byte USB_MASS_STORAGE_CLASS = (byte) 8;



    
    public static final byte USB_SMART_CARD_CLASS = (byte) 11;



    
    public static final byte USB_VIDEO_CLASS = (byte) 14;



    
    public static final byte USB_AUDIO_VIDEO_CLASS = (byte) 16;



    
    public static final byte USB_WIRELESS_CLASS = (byte) 224;



    private UsbDeviceConstants() {}

}