
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/content_settings/core/common/cookie_controls_enforcement.h

package org.chromium.components.content_settings;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    CookieControlsEnforcement.NO_ENFORCEMENT, CookieControlsEnforcement.ENFORCED_BY_POLICY,
    CookieControlsEnforcement.ENFORCED_BY_EXTENSION,
    CookieControlsEnforcement.ENFORCED_BY_COOKIE_SETTING,
    CookieControlsEnforcement.ENFORCED_BY_TPCD_GRANT, CookieControlsEnforcement.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface CookieControlsEnforcement {
  int NO_ENFORCEMENT = 0;
  int ENFORCED_BY_POLICY = 1;
  int ENFORCED_BY_EXTENSION = 2;
  int ENFORCED_BY_COOKIE_SETTING = 3;
  int ENFORCED_BY_TPCD_GRANT = 4;
  int MAX_VALUE = ENFORCED_BY_TPCD_GRANT;
}
