
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/content_settings/core/common/cookie_controls_breakage_confidence_level.h

package org.chromium.components.content_settings;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    CookieControlsBreakageConfidenceLevel.UNINITIALIZED, CookieControlsBreakageConfidenceLevel.LOW,
    CookieControlsBreakageConfidenceLevel.MEDIUM, CookieControlsBreakageConfidenceLevel.HIGH
})
@Retention(RetentionPolicy.SOURCE)
public @interface CookieControlsBreakageConfidenceLevel {
  int UNINITIALIZED = 0;
  int LOW = 1;
  int MEDIUM = 2;
  int HIGH = 3;
}
