// DisplayMode.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/display/mojom/display_mode.mojom
//

package org.chromium.display.mojom;

import androidx.annotation.IntDef;


public final class DisplayMode extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 40;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(40, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public org.chromium.gfx.mojom.Size size;
    public boolean isInterlaced;
    public float refreshRate;
    public int htotal;
    public int vtotal;
    public int clock;

    private DisplayMode(int version) {
        super(STRUCT_SIZE, version);
    }

    public DisplayMode() {
        this(0);
    }

    public static DisplayMode deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static DisplayMode deserialize(java.nio.ByteBuffer data) {
        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static DisplayMode decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        DisplayMode result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            final int elementsOrVersion = mainDataHeader.elementsOrVersion;
            result = new DisplayMode(elementsOrVersion);
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(8, false);
                result.size = org.chromium.gfx.mojom.Size.decode(decoder1);
                }
                {
                    
                result.isInterlaced = decoder0.readBoolean(16, 0);
                }
                {
                    
                result.refreshRate = decoder0.readFloat(20);
                }
                {
                    
                result.htotal = decoder0.readInt(24);
                }
                {
                    
                result.vtotal = decoder0.readInt(28);
                }
                {
                    
                result.clock = decoder0.readInt(32);
                }

        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(this.size, 8, false);
        
        encoder0.encode(this.isInterlaced, 16, 0);
        
        encoder0.encode(this.refreshRate, 20);
        
        encoder0.encode(this.htotal, 24);
        
        encoder0.encode(this.vtotal, 28);
        
        encoder0.encode(this.clock, 32);
    }
}