
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/autofill/core/browser/metrics/payments/mandatory_reauth_metrics.h

package org.chromium.components.autofill;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    MandatoryReauthAuthenticationFlowEvent.UNKNOWN,
    MandatoryReauthAuthenticationFlowEvent.FLOW_STARTED,
    MandatoryReauthAuthenticationFlowEvent.FLOW_SUCCEEDED,
    MandatoryReauthAuthenticationFlowEvent.FLOW_FAILED,
    MandatoryReauthAuthenticationFlowEvent.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface MandatoryReauthAuthenticationFlowEvent {
  int UNKNOWN = 0;
  /**
   * User authentication flow started.
   */
  int FLOW_STARTED = 1;
  /**
   * User authentication flow succeeded.
   */
  int FLOW_SUCCEEDED = 2;
  /**
   * User authentication flow failed.
   */
  int FLOW_FAILED = 3;
  int MAX_VALUE = FLOW_FAILED;
}
