
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/autofill/core/browser/ui/payments/payments_bubble_closed_reasons.h

package org.chromium.components.autofill;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    PaymentsBubbleClosedReason.UNKNOWN, PaymentsBubbleClosedReason.ACCEPTED,
    PaymentsBubbleClosedReason.CANCELLED, PaymentsBubbleClosedReason.CLOSED,
    PaymentsBubbleClosedReason.NOT_INTERACTED, PaymentsBubbleClosedReason.LOST_FOCUS
})
@Retention(RetentionPolicy.SOURCE)
public @interface PaymentsBubbleClosedReason {
  /**
   * Bubble closed reason not specified.
   */
  int UNKNOWN = 0;
  /**
   * The user explicitly accepted the bubble.
   */
  int ACCEPTED = 1;
  /**
   * The user explicitly cancelled the bubble.
   */
  int CANCELLED = 2;
  /**
   * The user explicitly closed the bubble (via the close button or the ESC).
   */
  int CLOSED = 3;
  /**
   * The bubble was not interacted.
   */
  int NOT_INTERACTED = 4;
  /**
   * The bubble lost focus and was deactivated.
   */
  int LOST_FOCUS = 5;
}
