
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/autofill/core/browser/metrics/payments/virtual_card_enrollment_metrics.h

package org.chromium.components.autofill;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    VirtualCardEnrollmentLinkType.VIRTUAL_CARD_ENROLLMENT_GOOGLE_PAYMENTS_TOS_LINK,
    VirtualCardEnrollmentLinkType.VIRTUAL_CARD_ENROLLMENT_ISSUER_TOS_LINK,
    VirtualCardEnrollmentLinkType.VIRTUAL_CARD_ENROLLMENT_LEARN_MORE_LINK,
    VirtualCardEnrollmentLinkType.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface VirtualCardEnrollmentLinkType {
  /**
   * These values are persisted to logs. Entries should not be renumbered and numeric values should
   * never be reused. User selected the Google Payments terms of service link.
   */
  int VIRTUAL_CARD_ENROLLMENT_GOOGLE_PAYMENTS_TOS_LINK = 0;
  /**
   * User selected the issuer terms of service link.
   */
  int VIRTUAL_CARD_ENROLLMENT_ISSUER_TOS_LINK = 1;
  /**
   * User selected the learn more about virtual cards link.
   */
  int VIRTUAL_CARD_ENROLLMENT_LEARN_MORE_LINK = 2;
  int MAX_VALUE = VIRTUAL_CARD_ENROLLMENT_LEARN_MORE_LINK;
}
