
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/autofill/core/browser/data_model/credit_card.h

package org.chromium.components.autofill;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    VirtualCardEnrollmentState.UNSPECIFIED, VirtualCardEnrollmentState.UNENROLLED,
    VirtualCardEnrollmentState.ENROLLED, VirtualCardEnrollmentState.UNENROLLED_AND_NOT_ELIGIBLE,
    VirtualCardEnrollmentState.UNENROLLED_AND_ELIGIBLE
})
@Retention(RetentionPolicy.SOURCE)
public @interface VirtualCardEnrollmentState {
  /**
   * State unspecified. This is the default value of this enum. Should not be ever used with cards.
   */
  int UNSPECIFIED = 0;
  /**
   * Deprecated. Card is not enrolled and does not have related virtual card.
   */
  int UNENROLLED = 1;
  /**
   * Card is enrolled and has related virtual cards.
   */
  int ENROLLED = 2;
  /**
   * Card is not enrolled and is not eligible for enrollment.
   */
  int UNENROLLED_AND_NOT_ELIGIBLE = 3;
  /**
   * Card is not enrolled but is eligible for enrollment.
   */
  int UNENROLLED_AND_ELIGIBLE = 4;
}
