
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/autofill/core/browser/payments/card_unmask_challenge_option.h

package org.chromium.chrome.browser.ui.autofill;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    CardUnmaskChallengeOptionType.UNKNOWN_TYPE, CardUnmaskChallengeOptionType.SMS_OTP,
    CardUnmaskChallengeOptionType.CVC, CardUnmaskChallengeOptionType.EMAIL_OTP,
    CardUnmaskChallengeOptionType.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface CardUnmaskChallengeOptionType {
  /**
   * Default value, should never be used.
   */
  int UNKNOWN_TYPE = 0;
  /**
   * SMS OTP authentication.
   */
  int SMS_OTP = 1;
  /**
   * CVC authentication.
   */
  int CVC = 2;
  /**
   * Email OTP authentication.
   */
  int EMAIL_OTP = 3;
  int MAX_VALUE = EMAIL_OTP;
}
