// SourceRegistrationError.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     components/attribution_reporting/source_registration_error.mojom
//

package org.chromium.attribution_reporting.mojom;

import androidx.annotation.IntDef;

public final class SourceRegistrationError {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        SourceRegistrationError.INVALID_JSON,
        SourceRegistrationError.ROOT_WRONG_TYPE,
        SourceRegistrationError.DESTINATION_MISSING,
        SourceRegistrationError.DESTINATION_WRONG_TYPE,
        SourceRegistrationError.DESTINATION_UNTRUSTWORTHY,
        SourceRegistrationError.DESTINATION_LIST_TOO_LONG,
        SourceRegistrationError.FILTER_DATA_WRONG_TYPE,
        SourceRegistrationError.FILTER_DATA_TOO_MANY_KEYS,
        SourceRegistrationError.FILTER_DATA_HAS_SOURCE_TYPE_KEY,
        SourceRegistrationError.FILTER_DATA_HAS_LOOKBACK_WINDOW_KEY,
        SourceRegistrationError.FILTER_DATA_KEY_TOO_LONG,
        SourceRegistrationError.FILTER_DATA_LIST_WRONG_TYPE,
        SourceRegistrationError.FILTER_DATA_LIST_TOO_LONG,
        SourceRegistrationError.FILTER_DATA_VALUE_WRONG_TYPE,
        SourceRegistrationError.FILTER_DATA_VALUE_TOO_LONG,
        SourceRegistrationError.AGGREGATION_KEYS_WRONG_TYPE,
        SourceRegistrationError.AGGREGATION_KEYS_TOO_MANY_KEYS,
        SourceRegistrationError.AGGREGATION_KEYS_KEY_TOO_LONG,
        SourceRegistrationError.AGGREGATION_KEYS_VALUE_WRONG_TYPE,
        SourceRegistrationError.AGGREGATION_KEYS_VALUE_WRONG_FORMAT,
        SourceRegistrationError.SOURCE_EVENT_ID_VALUE_INVALID,
        SourceRegistrationError.PRIORITY_VALUE_INVALID,
        SourceRegistrationError.EXPIRY_VALUE_INVALID,
        SourceRegistrationError.EVENT_REPORT_WINDOW_VALUE_INVALID,
        SourceRegistrationError.AGGREGATABLE_REPORT_WINDOW_VALUE_INVALID,
        SourceRegistrationError.MAX_EVENT_LEVEL_REPORTS_VALUE_INVALID,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_WRONG_TYPE,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_START_TIME_WRONG_TYPE,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_START_TIME_INVALID,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_END_TIMES_MISSING,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_END_TIMES_WRONG_TYPE,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_END_TIMES_LIST_EMPTY,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_END_TIMES_LIST_TOO_LONG,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_END_TIME_VALUE_WRONG_TYPE,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_END_TIME_VALUE_INVALID,
        SourceRegistrationError.EVENT_REPORT_WINDOWS_END_TIME_DURATION_LTE_START,
        SourceRegistrationError.BOTH_EVENT_REPORT_WINDOW_FIELDS_FOUND})
    public @interface EnumType {}

    public static final int INVALID_JSON = 0;
    public static final int ROOT_WRONG_TYPE = 1;
    public static final int DESTINATION_MISSING = 2;
    public static final int DESTINATION_WRONG_TYPE = 3;
    public static final int DESTINATION_UNTRUSTWORTHY = 4;
    public static final int DESTINATION_LIST_TOO_LONG = 18;
    public static final int FILTER_DATA_WRONG_TYPE = 5;
    public static final int FILTER_DATA_TOO_MANY_KEYS = 6;
    public static final int FILTER_DATA_HAS_SOURCE_TYPE_KEY = 7;
    public static final int FILTER_DATA_HAS_LOOKBACK_WINDOW_KEY = 24;
    public static final int FILTER_DATA_KEY_TOO_LONG = 8;
    public static final int FILTER_DATA_LIST_WRONG_TYPE = 9;
    public static final int FILTER_DATA_LIST_TOO_LONG = 10;
    public static final int FILTER_DATA_VALUE_WRONG_TYPE = 11;
    public static final int FILTER_DATA_VALUE_TOO_LONG = 12;
    public static final int AGGREGATION_KEYS_WRONG_TYPE = 13;
    public static final int AGGREGATION_KEYS_TOO_MANY_KEYS = 14;
    public static final int AGGREGATION_KEYS_KEY_TOO_LONG = 15;
    public static final int AGGREGATION_KEYS_VALUE_WRONG_TYPE = 16;
    public static final int AGGREGATION_KEYS_VALUE_WRONG_FORMAT = 17;
    public static final int SOURCE_EVENT_ID_VALUE_INVALID = 19;
    public static final int PRIORITY_VALUE_INVALID = 20;
    public static final int EXPIRY_VALUE_INVALID = 21;
    public static final int EVENT_REPORT_WINDOW_VALUE_INVALID = 22;
    public static final int AGGREGATABLE_REPORT_WINDOW_VALUE_INVALID = 23;
    public static final int MAX_EVENT_LEVEL_REPORTS_VALUE_INVALID = 25;
    public static final int EVENT_REPORT_WINDOWS_WRONG_TYPE = 26;
    public static final int EVENT_REPORT_WINDOWS_START_TIME_WRONG_TYPE = 27;
    public static final int EVENT_REPORT_WINDOWS_START_TIME_INVALID = 28;
    public static final int EVENT_REPORT_WINDOWS_END_TIMES_MISSING = 29;
    public static final int EVENT_REPORT_WINDOWS_END_TIMES_WRONG_TYPE = 30;
    public static final int EVENT_REPORT_WINDOWS_END_TIMES_LIST_EMPTY = 31;
    public static final int EVENT_REPORT_WINDOWS_END_TIMES_LIST_TOO_LONG = 32;
    public static final int EVENT_REPORT_WINDOWS_END_TIME_VALUE_WRONG_TYPE = 33;
    public static final int EVENT_REPORT_WINDOWS_END_TIME_VALUE_INVALID = 34;
    public static final int EVENT_REPORT_WINDOWS_END_TIME_DURATION_LTE_START = 35;
    public static final int BOTH_EVENT_REPORT_WINDOW_FIELDS_FOUND = 36;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 36;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 36;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private SourceRegistrationError() {}
}