// ClickModifiers.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/base/mojom/window_open_disposition.mojom
//

package org.chromium.ui.mojom;

import androidx.annotation.IntDef;


public final class ClickModifiers extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 16;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(16, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public boolean middleButton;
    public boolean altKey;
    public boolean ctrlKey;
    public boolean metaKey;
    public boolean shiftKey;

    private ClickModifiers(int version) {
        super(STRUCT_SIZE, version);
    }

    public ClickModifiers() {
        this(0);
    }

    public static ClickModifiers deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static ClickModifiers deserialize(java.nio.ByteBuffer data) {
        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static ClickModifiers decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        ClickModifiers result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            final int elementsOrVersion = mainDataHeader.elementsOrVersion;
            result = new ClickModifiers(elementsOrVersion);
                {
                    
                result.middleButton = decoder0.readBoolean(8, 0);
                }
                {
                    
                result.altKey = decoder0.readBoolean(8, 1);
                }
                {
                    
                result.ctrlKey = decoder0.readBoolean(8, 2);
                }
                {
                    
                result.metaKey = decoder0.readBoolean(8, 3);
                }
                {
                    
                result.shiftKey = decoder0.readBoolean(8, 4);
                }

        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(this.middleButton, 8, 0);
        
        encoder0.encode(this.altKey, 8, 1);
        
        encoder0.encode(this.ctrlKey, 8, 2);
        
        encoder0.encode(this.metaKey, 8, 3);
        
        encoder0.encode(this.shiftKey, 8, 4);
    }
}