// ShapeDetectionServiceConstants.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/shape_detection/public/mojom/shape_detection_service.mojom
//

package org.chromium.shape_detection.mojom;

import androidx.annotation.IntDef;

public final class ShapeDetectionServiceConstants {


    
    public static final int SHAPE_DETECTION_SANDBOX = (int) org.chromium.sandbox.mojom.Sandbox.GPU;



    private ShapeDetectionServiceConstants() {}

}