
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/feature_engagement/public/tracker.h

package org.chromium.components.feature_engagement;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    SnoozeAction.SNOOZED, SnoozeAction.DISMISSED, SnoozeAction.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface SnoozeAction {
  /**
   * User chose to snooze the IPH.
   */
  int SNOOZED = 1;
  /**
   * User chose to dismiss the IPH.
   */
  int DISMISSED = 2;
  /**
   * Constant used by the histogram macros.
   */
  int MAX_VALUE = DISMISSED;
}
