// GpuDiskCacheHandle.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     gpu/ipc/common/gpu_disk_cache_type.mojom
//

package org.chromium.gpu.mojom;

import androidx.annotation.IntDef;


public final class GpuDiskCacheHandle extends org.chromium.mojo.bindings.Union {

    public static final class Tag {
        public static final int GlShaderHandle = 0;
        public static final int DawnWebgpuHandle = 1;
    };
    private GpuDiskCacheGlShaderHandle mGlShaderHandle;
    private GpuDiskCacheDawnWebGpuHandle mDawnWebgpuHandle;

    public void setGlShaderHandle(GpuDiskCacheGlShaderHandle glShaderHandle) {
        this.mTag = Tag.GlShaderHandle;
        this.mGlShaderHandle = glShaderHandle;
    }

    public GpuDiskCacheGlShaderHandle getGlShaderHandle() {
        assert this.mTag == Tag.GlShaderHandle;
        return this.mGlShaderHandle;
    }

    public void setDawnWebgpuHandle(GpuDiskCacheDawnWebGpuHandle dawnWebgpuHandle) {
        this.mTag = Tag.DawnWebgpuHandle;
        this.mDawnWebgpuHandle = dawnWebgpuHandle;
    }

    public GpuDiskCacheDawnWebGpuHandle getDawnWebgpuHandle() {
        assert this.mTag == Tag.DawnWebgpuHandle;
        return this.mDawnWebgpuHandle;
    }


    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder0, int offset) {
        encoder0.encode(org.chromium.mojo.bindings.BindingsHelper.UNION_SIZE, offset);
        encoder0.encode(this.mTag, offset + 4);
        switch (mTag) {
            case Tag.GlShaderHandle: {
                
                encoder0.encode(this.mGlShaderHandle, offset + 8, false);
                break;
            }
            case Tag.DawnWebgpuHandle: {
                
                encoder0.encode(this.mDawnWebgpuHandle, offset + 8, false);
                break;
            }
            default: {
                break;
            }
        }
    }

    public static GpuDiskCacheHandle deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message).decoderForSerializedUnion(), 0);
    }

    public static final GpuDiskCacheHandle decode(org.chromium.mojo.bindings.Decoder decoder0, int offset) {
        org.chromium.mojo.bindings.DataHeader dataHeader = decoder0.readDataHeaderForUnion(offset);
        if (dataHeader.size == 0) {
            return null;
        }
        GpuDiskCacheHandle result = new GpuDiskCacheHandle();
        switch (dataHeader.elementsOrVersion) {
            case Tag.GlShaderHandle: {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(offset + org.chromium.mojo.bindings.DataHeader.HEADER_SIZE, false);
                result.mGlShaderHandle = GpuDiskCacheGlShaderHandle.decode(decoder1);
                result.mTag = Tag.GlShaderHandle;
                break;
            }
            case Tag.DawnWebgpuHandle: {
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(offset + org.chromium.mojo.bindings.DataHeader.HEADER_SIZE, false);
                result.mDawnWebgpuHandle = GpuDiskCacheDawnWebGpuHandle.decode(decoder1);
                result.mTag = Tag.DawnWebgpuHandle;
                break;
            }
            default: {
                break;
            }
        }
        return result;
    }
}