
// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/metrics/stability_metrics_helper.h

package org.chromium.components.metrics;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    StabilityEventType.PAGE_LOAD, StabilityEventType.RENDERER_CRASH,
    StabilityEventType.EXTENSION_CRASH, StabilityEventType.LAUNCH, StabilityEventType.BROWSER_CRASH,
    StabilityEventType.RENDERER_FAILED_LAUNCH, StabilityEventType.EXTENSION_RENDERER_FAILED_LAUNCH,
    StabilityEventType.RENDERER_LAUNCH, StabilityEventType.EXTENSION_RENDERER_LAUNCH,
    StabilityEventType.GPU_CRASH, StabilityEventType.UTILITY_CRASH,
    StabilityEventType.UTILITY_LAUNCH, StabilityEventType.MAX_VALUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface StabilityEventType {
  int PAGE_LOAD = 2;
  int RENDERER_CRASH = 3;
  /**
   * kRendererHang = 4,  // Removed due to disuse and correctness issues.
   */
  int EXTENSION_CRASH = 5;
  /**
   * kChildProcessCrash = 6,  // Removed due to disuse and alternative metrics.
   */
  int LAUNCH = 15;
  int BROWSER_CRASH = 16;
  /**
   * kIncompleteShutdown = 17,  // Removed due to disuse and correctness issues. kPluginCrash = 22,
   * // Removed due to plugin deprecation.
   */
  int RENDERER_FAILED_LAUNCH = 24;
  int EXTENSION_RENDERER_FAILED_LAUNCH = 25;
  int RENDERER_LAUNCH = 26;
  int EXTENSION_RENDERER_LAUNCH = 27;
  int GPU_CRASH = 31;
  int UTILITY_CRASH = 32;
  int UTILITY_LAUNCH = 33;
  int MAX_VALUE = UTILITY_LAUNCH;
}
