// MediaServiceConstants.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/mojom/media_service.mojom
//

package org.chromium.media.mojom;

import androidx.annotation.IntDef;

public final class MediaServiceConstants {


    
    public static final int MEDIA_SANDBOX = (int) org.chromium.sandbox.mojom.Sandbox.GPU;



    private MediaServiceConstants() {}

}