// AbslStatusCode.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     mojo/public/mojom/base/absl_status.mojom
//

package org.chromium.mojo_base.mojom;

import androidx.annotation.IntDef;

public final class AbslStatusCode {
    private static final boolean IS_EXTENSIBLE = false;
    @IntDef({

        AbslStatusCode.OK,
        AbslStatusCode.CANCELLED,
        AbslStatusCode.UNKNOWN,
        AbslStatusCode.INVALID_ARGUMENT,
        AbslStatusCode.DEADLINE_EXCEEDED,
        AbslStatusCode.NOT_FOUND,
        AbslStatusCode.ALREADY_EXISTS,
        AbslStatusCode.PERMISSION_DENIED,
        AbslStatusCode.RESOURCE_EXHAUSTED,
        AbslStatusCode.FAILED_PRECONDITION,
        AbslStatusCode.ABORTED,
        AbslStatusCode.OUT_OF_RANGE,
        AbslStatusCode.UNIMPLEMENTED,
        AbslStatusCode.INTERNAL,
        AbslStatusCode.UNAVAILABLE,
        AbslStatusCode.DATA_LOSS,
        AbslStatusCode.UNAUTHENTICATED})
    public @interface EnumType {}

    public static final int OK = 0;
    public static final int CANCELLED = 1;
    public static final int UNKNOWN = 2;
    public static final int INVALID_ARGUMENT = 3;
    public static final int DEADLINE_EXCEEDED = 4;
    public static final int NOT_FOUND = 5;
    public static final int ALREADY_EXISTS = 6;
    public static final int PERMISSION_DENIED = 7;
    public static final int RESOURCE_EXHAUSTED = 8;
    public static final int FAILED_PRECONDITION = 9;
    public static final int ABORTED = 10;
    public static final int OUT_OF_RANGE = 11;
    public static final int UNIMPLEMENTED = 12;
    public static final int INTERNAL = 13;
    public static final int UNAVAILABLE = 14;
    public static final int DATA_LOSS = 15;
    public static final int UNAUTHENTICATED = 16;
    public static final int MIN_VALUE = 0;
    public static final int MAX_VALUE = 16;

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 16;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    public static int toKnownValue(int value) {
      return value;
    }

    private AbslStatusCode() {}
}